from screen_module import Screen

screen = Screen("result.json")
screen.setup()
screen.print()
input()
screen.add_player("Johan")
screen.add_player("Anders")
screen.add_player("Erik")
screen.print_players()
screen.print()
input()
screen.next_turn()
screen.print()
input()
screen.next_turn()
screen.print()
input()
screen.next_turn()
screen.print()
input()
screen.next_turn()
screen.print()
screen.add_year("Johan", "1234")
screen.add_year("Johan", "1334")
screen.add_year("Johan", "1134")
screen.add_year("Anders", "1534")
screen.add_year("Anders", "1539")
screen.add_year("Erik", "1634")
screen.print_years()
screen.print()
input()
screen.add_year("Erik", "1434")
screen.print_years()
screen.print()
input()
screen.add_year("Erik", "1634")
screen.print_years()
screen.print()
input()
screen.add_year("Erik", "1434")
screen.print_years()
screen.print()
input()
screen.message("Title 1",
                   "A super long message should be devided into smaller chunkes and printed line by line like this (hopefully)", "This is a prompt message, telling you what to write")
input()

screen.message("Title 2!",
                   "Now I'll try an even longer message, one that spans multiple lines and seems to go on forever and ever and ever and ever and ever and ever and ever. It just never stops, it's here to show that we can handle this.", "This is a prompt message, telling you what to write")
input()
screen.add_year("Erik", "1878")
screen.print_years()
screen.print()
input()
screen.add_year("Erik", "1945")
screen.print_years()
screen.print()
input()
screen.message("Title 2!",
                   "Now I'll try A short message without prompt")
input()
screen.message("Title 2!",
                   "With prompt", "the prompt")
input()
